services:
  Wpci\Core\:
    resource: '../core/*'
    exclude: '../core/{App.php, Contracts, Exceptions, Facades, Helpers}'

  Wpci\Core\WpFrontController:
    public: true
    arguments: ['@service_container']