services:
  _defaults: { public: true }

  Wpci\Core\:
    resource: '../core/*'
    exclude: '../core/{App.php, Contracts, Exceptions, Facades, Helpers}'

  Wpci\Core\WpFrontController:
    public: true
    arguments: ['@service_container']

  Wpci\Core\Render\View:
    public: true
    arguments: ['@Wpci\Core\Render\MustacheTemplate', '@Wpci\Core\Http\WpResponse']